# Generated by Django 3.0.8 on 2020-08-14 22:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_connect'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connect',
            new_name='Comment',
        ),
    ]
